name: Continuous Integration
run-name: Node.js CI

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'
      - name: Clean install
        run: npm ci
      - name: Run linter
        run: npm run lint
      - name: Compile typescript
        run: npm run compile
      - name: Jest unit tests
        run: npm run unit:tests
      - name: Test coverage
        run: npm run test:coverage
      - name: Build App
        run: npm run build --if-present
      - name: Archive Next.js build
        uses: actions/upload-artifact@v3
        with:
            name: next.js-build-18.x
            path: .next/
            retention-days: 14

      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report-18.x
          path: docs/coverage/index.html
          retention-days: 14